// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sessions/v1/events.proto

package sessionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionAdded mirrors zitadel/zitadel
// internal/repository/session.AddedEvent.
type SessionAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgent     *UserAgent             `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAdded) Reset() {
	*x = SessionAdded{}
	mi := &file_sessions_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAdded) ProtoMessage() {}

func (x *SessionAdded) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAdded.ProtoReflect.Descriptor instead.
func (*SessionAdded) Descriptor() ([]byte, []int) {
	return file_sessions_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SessionAdded) GetUserAgent() *UserAgent {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

// SessionUserChecked mirrors
// internal/repository/session.UserCheckedEvent.
type SessionUserChecked struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserResourceOwner string                 `protobuf:"bytes,2,opt,name=user_resource_owner,json=userResourceOwner,proto3" json:"user_resource_owner,omitempty"`
	CheckedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	PreferredLanguage *string                `protobuf:"bytes,4,opt,name=preferred_language,json=preferredLanguage,proto3,oneof" json:"preferred_language,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionUserChecked) Reset() {
	*x = SessionUserChecked{}
	mi := &file_sessions_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUserChecked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUserChecked) ProtoMessage() {}

func (x *SessionUserChecked) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUserChecked.ProtoReflect.Descriptor instead.
func (*SessionUserChecked) Descriptor() ([]byte, []int) {
	return file_sessions_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *SessionUserChecked) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionUserChecked) GetUserResourceOwner() string {
	if x != nil {
		return x.UserResourceOwner
	}
	return ""
}

func (x *SessionUserChecked) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *SessionUserChecked) GetPreferredLanguage() string {
	if x != nil && x.PreferredLanguage != nil {
		return *x.PreferredLanguage
	}
	return ""
}

var File_sessions_v1_events_proto protoreflect.FileDescriptor

const file_sessions_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18sessions/v1/events.proto\x12\vsessions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17sessions/v1/types.proto\"Y\n" +
	"\fSessionAdded\x12:\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\v2\x16.sessions.v1.UserAgentH\x00R\tuserAgent\x88\x01\x01B\r\n" +
	"\v_user_agent\"\xe3\x01\n" +
	"\x12SessionUserChecked\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13user_resource_owner\x18\x02 \x01(\tR\x11userResourceOwner\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x122\n" +
	"\x12preferred_language\x18\x04 \x01(\tH\x00R\x11preferredLanguage\x88\x01\x01B\x15\n" +
	"\x13_preferred_languageB\xba\x01\n" +
	"\x0fcom.sessions.v1B\vEventsProtoP\x01ZMgithub.com/medincident/medincident-zitadel-actions/pkg/sessions/v1;sessionsv1\xa2\x02\x03SXX\xaa\x02\vSessions.V1\xca\x02\vSessions\\V1\xe2\x02\x17Sessions\\V1\\GPBMetadata\xea\x02\fSessions::V1b\x06proto3"

var (
	file_sessions_v1_events_proto_rawDescOnce sync.Once
	file_sessions_v1_events_proto_rawDescData []byte
)

func file_sessions_v1_events_proto_rawDescGZIP() []byte {
	file_sessions_v1_events_proto_rawDescOnce.Do(func() {
		file_sessions_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_v1_events_proto_rawDesc), len(file_sessions_v1_events_proto_rawDesc)))
	})
	return file_sessions_v1_events_proto_rawDescData
}

var file_sessions_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sessions_v1_events_proto_goTypes = []any{
	(*SessionAdded)(nil),          // 0: sessions.v1.SessionAdded
	(*SessionUserChecked)(nil),    // 1: sessions.v1.SessionUserChecked
	(*UserAgent)(nil),             // 2: sessions.v1.UserAgent
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sessions_v1_events_proto_depIdxs = []int32{
	2, // 0: sessions.v1.SessionAdded.user_agent:type_name -> sessions.v1.UserAgent
	3, // 1: sessions.v1.SessionUserChecked.checked_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sessions_v1_events_proto_init() }
func file_sessions_v1_events_proto_init() {
	if File_sessions_v1_events_proto != nil {
		return
	}
	file_sessions_v1_types_proto_init()
	file_sessions_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_sessions_v1_events_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_v1_events_proto_rawDesc), len(file_sessions_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sessions_v1_events_proto_goTypes,
		DependencyIndexes: file_sessions_v1_events_proto_depIdxs,
		MessageInfos:      file_sessions_v1_events_proto_msgTypes,
	}.Build()
	File_sessions_v1_events_proto = out.File
	file_sessions_v1_events_proto_goTypes = nil
	file_sessions_v1_events_proto_depIdxs = nil
}
