// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/envelope.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope mirrors the Zitadel Actions v2 event webhook body 1:1 and
// carries the typed event payload in payload. Field names and
// semantics match Zitadel's internal ContextInfoEvent struct in
// zitadel/zitadel internal/repository/execution/queue.go — do not
// rename or re-type without re-verifying upstream.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType string                 `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	ResourceOwner string                 `protobuf:"bytes,3,opt,name=resource_owner,json=resourceOwner,proto3" json:"resource_owner,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Envelope) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *Envelope) GetResourceOwner() string {
	if x != nil {
		return x.ResourceOwner
	}
	return ""
}

func (x *Envelope) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Envelope) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Envelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Envelope) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Envelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_events_v1_envelope_proto protoreflect.FileDescriptor

const file_events_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18events/v1/envelope.proto\x12\tevents.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x02\n" +
	"\bEnvelope\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x02 \x01(\tR\raggregateType\x12%\n" +
	"\x0eresource_owner\x18\x03 \x01(\tR\rresourceOwner\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12.\n" +
	"\apayload\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyR\apayloadB\xae\x01\n" +
	"\rcom.events.v1B\rEnvelopeProtoP\x01ZIgithub.com/medincident/medincident-zitadel-actions/pkg/events/v1;eventsv1\xa2\x02\x03EXX\xaa\x02\tEvents.V1\xca\x02\tEvents\\V1\xe2\x02\x15Events\\V1\\GPBMetadata\xea\x02\n" +
	"Events::V1b\x06proto3"

var (
	file_events_v1_envelope_proto_rawDescOnce sync.Once
	file_events_v1_envelope_proto_rawDescData []byte
)

func file_events_v1_envelope_proto_rawDescGZIP() []byte {
	file_events_v1_envelope_proto_rawDescOnce.Do(func() {
		file_events_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)))
	})
	return file_events_v1_envelope_proto_rawDescData
}

var file_events_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: events.v1.Envelope
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
}
var file_events_v1_envelope_proto_depIdxs = []int32{
	1, // 0: events.v1.Envelope.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: events.v1.Envelope.payload:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_v1_envelope_proto_init() }
func file_events_v1_envelope_proto_init() {
	if File_events_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_envelope_proto_goTypes,
		DependencyIndexes: file_events_v1_envelope_proto_depIdxs,
		MessageInfos:      file_events_v1_envelope_proto_msgTypes,
	}.Build()
	File_events_v1_envelope_proto = out.File
	file_events_v1_envelope_proto_goTypes = nil
	file_events_v1_envelope_proto_depIdxs = nil
}
