name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "**.proto"
      - "buf.gen.yaml"
      - "buf.gen.docs.yaml"
      - "api/proto/buf.yaml"
      - "Taskfile.yml"
      - "Makefile"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "**.proto"
      - "buf.gen.yaml"
      - "buf.gen.docs.yaml"
      - "api/proto/buf.yaml"
      - "Taskfile.yml"
      - "Makefile"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
      - run: task proto:fmt:check
      - run: task proto:lint
      - run: task gen:check
      - run: task fmt:check
      - run: task lint
      - run: task vuln
      - run: task test
